---
- name: Install and configure Nginx
  hosts: web
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create custom index.html
      copy:
        content: "Hello, DevOps Aston!"
        dest: /var/www/html/index.html
      notify: restart nginx

    - name: Start Nginx service
      service:
        name: nginx
        state: started

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
